/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/cpu1.glb -o src/components/cpu1.jsx -k -r public
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/cpu1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="bone" position={[1.2, 0, 0.288]}>
        <mesh name="cube_6" geometry={nodes.cube_6.geometry} material={nodes.cube_6.material} position={[0.329, 0, 0.52]} rotation={[0, -0.34, 0]} />
        <mesh name="cube_7" geometry={nodes.cube_7.geometry} material={nodes.cube_7.material} />
        <mesh name="cube_8" geometry={nodes.cube_8.geometry} material={nodes.cube_8.material} position={[-0.105, 0, 0.543]} rotation={[0, -0.951, 0]} />
        <mesh name="cube_9" geometry={nodes.cube_9.geometry} material={nodes.cube_9.material} position={[-0.105, 0, 0.543]} rotation={[0, -Math.PI / 2, 0]} />
      </group>
      <mesh name="cube_4" geometry={nodes.cube_4.geometry} material={nodes.cube_4.material} />
      <mesh name="cube_5" geometry={nodes.cube_5.geometry} material={nodes.cube_5.material} />
      <mesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
      <mesh name="mesh_0_1" geometry={nodes.mesh_0_1.geometry} material={nodes.mesh_0_1.material} />
      <mesh name="mesh_0_2" geometry={nodes.mesh_0_2.geometry} material={nodes.mesh_0_2.material} />
      <mesh name="mesh_0_3" geometry={nodes.mesh_0_3.geometry} material={nodes.mesh_0_3.material} />
      <mesh name="mesh_0_4" geometry={nodes.mesh_0_4.geometry} material={nodes.mesh_0_4.material} />
      <mesh name="mesh_1" geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
      <mesh name="mesh_1_1" geometry={nodes.mesh_1_1.geometry} material={nodes.mesh_1_1.material} />
      <mesh name="mesh_1_2" geometry={nodes.mesh_1_2.geometry} material={nodes.mesh_1_2.material} />
      <mesh name="mesh_1_3" geometry={nodes.mesh_1_3.geometry} material={nodes.mesh_1_3.material} />
      <mesh name="mesh_1_4" geometry={nodes.mesh_1_4.geometry} material={nodes.mesh_1_4.material} />
      <mesh name="mesh_2" geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
      <mesh name="mesh_2_1" geometry={nodes.mesh_2_1.geometry} material={nodes.mesh_2_1.material} />
      <mesh name="mesh_2_2" geometry={nodes.mesh_2_2.geometry} material={nodes.mesh_2_2.material} />
      <mesh name="mesh_7" geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} />
      <mesh name="mesh_7_1" geometry={nodes.mesh_7_1.geometry} material={nodes.mesh_7_1.material} />
    </group>
  )
}

useGLTF.preload('/models/cpu1.glb')
