/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/logo.glb -o src/components√.jsx -k -r public
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/logo.glb')
  return (
    <group {...props} dispose={null}>
      <group name="hd" position={[0, -0.281, 0.047]}>
        <mesh name="Hd" geometry={nodes.Hd.geometry} material={nodes.Hd.material} position={[-0.053, 0.744, -0.047]} rotation={[0, Math.PI / 2, 0]} />
        <group name="Hd_1" position={[-0.053, 0.744, -0.047]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="mesh_19" geometry={nodes.mesh_19.geometry} material={nodes.mesh_19.material} />
          <mesh name="mesh_19_1" geometry={nodes.mesh_19_1.geometry} material={nodes.mesh_19_1.material} />
        </group>
        <mesh name="Hd_2" geometry={nodes.Hd_2.geometry} material={nodes.Hd_2.material} position={[-0.053, 0.744, -0.047]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Hd_3" geometry={nodes.Hd_3.geometry} material={nodes.Hd_3.material} position={[-0.053, 0.744, -0.047]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Hd_4" geometry={nodes.Hd_4.geometry} material={nodes.Hd_4.material} position={[-0.053, 0.744, -0.047]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Hd_5" geometry={nodes.Hd_5.geometry} material={nodes.Hd_5.material} position={[-0.053, 0.744, -0.047]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Hd_6" geometry={nodes.Hd_6.geometry} material={nodes.Hd_6.material} position={[-0.053, 0.744, -0.047]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Hd_7" geometry={nodes.Hd_7.geometry} material={nodes.Hd_7.material} position={[-0.053, 0.744, -0.047]} rotation={[0, Math.PI / 2, 0]} />
      </group>
      <group name="text_JCPC_2" position={[-0.452, 0.563, -0.078]}>
        <mesh name="text_J_C_P_C__" geometry={nodes.text_J_C_P_C__.geometry} material={nodes.text_J_C_P_C__.material} position={[0.125, 0, 0]} />
        <mesh name="text_J_C_P_C___1" geometry={nodes.text_J_C_P_C___1.geometry} material={nodes.text_J_C_P_C___1.material} position={[0.125, 0, 0]} />
        <mesh name="text_J_C_P_C___2" geometry={nodes.text_J_C_P_C___2.geometry} material={nodes.text_J_C_P_C___2.material} position={[0.125, 0, 0]} />
        <mesh name="text_J_C_P_C___3" geometry={nodes.text_J_C_P_C___3.geometry} material={nodes.text_J_C_P_C___3.material} position={[0.125, 0, 0]} />
        <mesh name="text_J_C_P_C___4" geometry={nodes.text_J_C_P_C___4.geometry} material={nodes.text_J_C_P_C___4.material} position={[0.125, 0, 0]} />
        <mesh name="text_J_C_P_C___5" geometry={nodes.text_J_C_P_C___5.geometry} material={nodes.text_J_C_P_C___5.material} position={[0.125, 0, 0]} />
        <mesh name="text_J_C_P_C___6" geometry={nodes.text_J_C_P_C___6.geometry} material={nodes.text_J_C_P_C___6.material} position={[0.125, 0, 0]} />
        <mesh name="text_J_C_P_C___7" geometry={nodes.text_J_C_P_C___7.geometry} material={nodes.text_J_C_P_C___7.material} position={[0.125, 0, 0]} />
        <mesh name="text_J_C_P_C___8" geometry={nodes.text_J_C_P_C___8.geometry} material={nodes.text_J_C_P_C___8.material} position={[0.125, 0, 0]} />
        <mesh name="text_J_C_P_C___9" geometry={nodes.text_J_C_P_C___9.geometry} material={nodes.text_J_C_P_C___9.material} position={[0.125, 0, 0]} />
        <mesh name="text_J_C_P_C___10" geometry={nodes.text_J_C_P_C___10.geometry} material={nodes.text_J_C_P_C___10.material} position={[0.125, 0, 0]} />
        <mesh name="text_J_C_P_C___11" geometry={nodes.text_J_C_P_C___11.geometry} material={nodes.text_J_C_P_C___11.material} position={[0.125, 0, 0]} />
        <mesh name="text_J_C_P_C___12" geometry={nodes.text_J_C_P_C___12.geometry} material={nodes.text_J_C_P_C___12.material} position={[0.125, 0, 0]} />
      </group>
      <group name="ฝาฝั่งboard" position={[-0.053, 0.462, 0]} rotation={[0, Math.PI / 2, 0]}>
        <mesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
        <mesh name="mesh_0_1" geometry={nodes.mesh_0_1.geometry} material={nodes.mesh_0_1.material} />
        <mesh name="mesh_0_2" geometry={nodes.mesh_0_2.geometry} material={nodes.mesh_0_2.material} />
      </group>
      <group name="ช่องหลัง" position={[-0.053, 0.462, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh name="mesh_1" geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
        <mesh name="mesh_1_1" geometry={nodes.mesh_1_1.geometry} material={nodes.mesh_1_1.material} />
        <mesh name="mesh_1_2" geometry={nodes.mesh_1_2.geometry} material={nodes.mesh_1_2.material} />
        <mesh name="mesh_1_3" geometry={nodes.mesh_1_3.geometry} material={nodes.mesh_1_3.material} />
        <mesh name="mesh_1_4" geometry={nodes.mesh_1_4.geometry} material={nodes.mesh_1_4.material} />
      </group>
      <mesh name="หน้า" geometry={nodes.หน้า.geometry} material={nodes.หน้า.material} position={[-0.053, 0.462, 0]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="พื้น_case" geometry={nodes.พื้น_case.geometry} material={nodes.พื้น_case.material} position={[-0.053, 0.462, 0]} rotation={[0, Math.PI / 2, 0]} />
      <mesh name="พื้น_case_1" geometry={nodes.พื้น_case_1.geometry} material={nodes.พื้น_case_1.material} position={[-0.053, 0.462, 0]} rotation={[0, Math.PI / 2, 0]} />
      <mesh name="ล้อ1" geometry={nodes.ล้อ1.geometry} material={nodes.ล้อ1.material} position={[-0.156, 0.462, 0]} rotation={[Math.PI, 0.925, -Math.PI]} />
      <mesh name="ล้อ3" geometry={nodes.ล้อ3.geometry} material={nodes.ล้อ3.material} position={[-0.156, 0.462, 0]} rotation={[Math.PI, 0.925, -Math.PI]} />
      <mesh name="ล้อ4" geometry={nodes.ล้อ4.geometry} material={nodes.ล้อ4.material} position={[-0.053, 0.462, 0]} rotation={[0, Math.PI / 2, 0]} />
      <mesh name="ล้อ2" geometry={nodes.ล้อ2.geometry} material={nodes.ล้อ2.material} position={[-0.053, 0.462, 0]} rotation={[0, Math.PI / 2, 0]} />
      <group name="power" position={[-0.053, 0.462, 0]} rotation={[0, Math.PI / 2, 0]}>
        <mesh name="mesh_9" geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
        <mesh name="mesh_9_1" geometry={nodes.mesh_9_1.geometry} material={nodes.mesh_9_1.material} />
        <mesh name="mesh_9_2" geometry={nodes.mesh_9_2.geometry} material={nodes.mesh_9_2.material} />
      </group>
      <group name="ช่องเสียหมุด" position={[-0.053, 0.462, 0]} rotation={[0, Math.PI / 2, 0]}>
        <mesh name="mesh_10" geometry={nodes.mesh_10.geometry} material={nodes.mesh_10.material} />
        <mesh name="mesh_10_1" geometry={nodes.mesh_10_1.geometry} material={nodes.mesh_10_1.material} />
        <mesh name="mesh_10_2" geometry={nodes.mesh_10_2.geometry} material={nodes.mesh_10_2.material} />
      </group>
      <group name="ช่องเสียหมุด_1" position={[-0.053, 0.462, 0]} rotation={[0, Math.PI / 2, 0]}>
        <mesh name="mesh_11" geometry={nodes.mesh_11.geometry} material={nodes.mesh_11.material} />
        <mesh name="mesh_11_1" geometry={nodes.mesh_11_1.geometry} material={nodes.mesh_11_1.material} />
        <mesh name="mesh_11_2" geometry={nodes.mesh_11_2.geometry} material={nodes.mesh_11_2.material} />
        <mesh name="mesh_11_3" geometry={nodes.mesh_11_3.geometry} material={nodes.mesh_11_3.material} />
        <mesh name="mesh_11_4" geometry={nodes.mesh_11_4.geometry} material={nodes.mesh_11_4.material} />
      </group>
      <group name="board" position={[-0.053, 0.462, 0]} rotation={[0, Math.PI / 2, 0]}>
        <mesh name="mesh_12" geometry={nodes.mesh_12.geometry} material={nodes.mesh_12.material} />
        <mesh name="mesh_12_1" geometry={nodes.mesh_12_1.geometry} material={nodes.mesh_12_1.material} />
        <mesh name="mesh_12_2" geometry={nodes.mesh_12_2.geometry} material={nodes.mesh_12_2.material} />
      </group>
      <mesh name="port" geometry={nodes.port.geometry} material={nodes.port.material} position={[-0.053, 0.462, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="cpufan" geometry={nodes.cpufan.geometry} material={nodes.cpufan.material} position={[-0.053, 0.462, 0]} rotation={[0, Math.PI / 2, 0]} />
      <group name="cube" position={[-0.053, 0.462, 0]} rotation={[0, Math.PI / 2, 0]}>
        <mesh name="mesh_15" geometry={nodes.mesh_15.geometry} material={nodes.mesh_15.material} />
        <mesh name="mesh_15_1" geometry={nodes.mesh_15_1.geometry} material={nodes.mesh_15_1.material} />
        <mesh name="mesh_15_2" geometry={nodes.mesh_15_2.geometry} material={nodes.mesh_15_2.material} />
        <mesh name="mesh_15_3" geometry={nodes.mesh_15_3.geometry} material={nodes.mesh_15_3.material} />
        <mesh name="mesh_15_4" geometry={nodes.mesh_15_4.geometry} material={nodes.mesh_15_4.material} />
      </group>
      <mesh name="cube_1" geometry={nodes.cube_1.geometry} material={nodes.cube_1.material} position={[-0.053, 0.462, 0]} rotation={[0, Math.PI / 2, 0]} />
      <mesh name="cube_2" geometry={nodes.cube_2.geometry} material={nodes.cube_2.material} position={[-0.053, 0.462, 0]} rotation={[0, Math.PI / 2, 0]} />
      <mesh name="cube_3" geometry={nodes.cube_3.geometry} material={nodes.cube_3.material} position={[-0.053, 0.462, 0]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="cube_4" geometry={nodes.cube_4.geometry} material={nodes.cube_4.material} position={[-0.053, 0.462, 0]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="cube_5" geometry={nodes.cube_5.geometry} material={nodes.cube_5.material} position={[-0.053, 0.462, 0]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh name="cube_6" geometry={nodes.cube_6.geometry} material={nodes.cube_6.material} position={[-0.053, 0.462, 0]} rotation={[0, -Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/models/logo.glb')
