/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/set1.glb -o src/components√.jsx -k -r public
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/set1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="พื้น_case" geometry={nodes.พื้น_case.geometry} material={nodes.พื้น_case.material} position={[0, 0.063, 0]} />
      <group name="หน้า" position={[0, -0.094, 0]} rotation={[0, Math.PI / 2, 0]}>
        <mesh name="mesh_1" geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
        <mesh name="mesh_1_1" geometry={nodes.mesh_1_1.geometry} material={nodes.mesh_1_1.material} />
      </group>
      <group name="ฝาฝั่งboard" position={[0, 0.063, 0]}>
        <mesh name="mesh_2" geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
        <mesh name="mesh_2_1" geometry={nodes.mesh_2_1.geometry} material={nodes.mesh_2_1.material} />
      </group>
      <group name="ช่องหลัง" position={[0, 0.063, 0]} rotation={[0, Math.PI / 2, 0]}>
        <mesh name="mesh_3" geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
        <mesh name="mesh_3_1" geometry={nodes.mesh_3_1.geometry} material={nodes.mesh_3_1.material} />
        <mesh name="mesh_3_2" geometry={nodes.mesh_3_2.geometry} material={nodes.mesh_3_2.material} />
      </group>
      <group name="พื้น_case_1" position={[0, 0.063, 0]}>
        <mesh name="mesh_4" geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
        <mesh name="mesh_4_1" geometry={nodes.mesh_4_1.geometry} material={nodes.mesh_4_1.material} />
        <mesh name="mesh_4_2" geometry={nodes.mesh_4_2.geometry} material={nodes.mesh_4_2.material} />
      </group>
      <mesh name="ล้อ1" geometry={nodes.ล้อ1.geometry} material={nodes.ล้อ1.material} position={[0, 0.063, 0]} />
      <mesh name="ล้อ3" geometry={nodes.ล้อ3.geometry} material={nodes.ล้อ3.material} position={[0, 0.063, 0]} />
      <mesh name="ล้อ4" geometry={nodes.ล้อ4.geometry} material={nodes.ล้อ4.material} position={[0, 0.063, 0]} />
      <mesh name="ล้อ2" geometry={nodes.ล้อ2.geometry} material={nodes.ล้อ2.material} position={[0, 0.063, 0]} />
      <group name="power" position={[0, 0.063, 0]}>
        <mesh name="mesh_9" geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
        <mesh name="mesh_9_1" geometry={nodes.mesh_9_1.geometry} material={nodes.mesh_9_1.material} />
        <mesh name="mesh_9_2" geometry={nodes.mesh_9_2.geometry} material={nodes.mesh_9_2.material} />
      </group>
      <mesh name="ช่องเสียหมุด" geometry={nodes.ช่องเสียหมุด.geometry} material={nodes.ช่องเสียหมุด.material} position={[0, 0.063, 0]} />
      <mesh name="ช่องเสียหมุด_1" geometry={nodes.ช่องเสียหมุด_1.geometry} material={nodes.ช่องเสียหมุด_1.material} position={[0, 0.063, 0]} />
      <mesh name="board" geometry={nodes.board.geometry} material={nodes.board.material} />
      <mesh name="port" geometry={nodes.port.geometry} material={nodes.port.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="cpufan" geometry={nodes.cpufan.geometry} material={nodes.cpufan.material} />
      <mesh name="mesh_15" geometry={nodes.mesh_15.geometry} material={nodes.mesh_15.material} />
      <mesh name="mesh_15_1" geometry={nodes.mesh_15_1.geometry} material={nodes.mesh_15_1.material} />
      <mesh name="mesh_15_2" geometry={nodes.mesh_15_2.geometry} material={nodes.mesh_15_2.material} />
      <mesh name="mesh_15_3" geometry={nodes.mesh_15_3.geometry} material={nodes.mesh_15_3.material} />
      <mesh name="mesh_15_4" geometry={nodes.mesh_15_4.geometry} material={nodes.mesh_15_4.material} />
      <mesh name="mesh_15_5" geometry={nodes.mesh_15_5.geometry} material={nodes.mesh_15_5.material} />
      <mesh name="cube_1" geometry={nodes.cube_1.geometry} material={nodes.cube_1.material} />
      <mesh name="cube_2" geometry={nodes.cube_2.geometry} material={nodes.cube_2.material} />
      <mesh name="Hd_1" geometry={nodes.Hd_1.geometry} material={nodes.Hd_1.material} />
      <mesh name="Hd_2" geometry={nodes.Hd_2.geometry} material={nodes.Hd_2.material} />
      <mesh name="Hd_3" geometry={nodes.Hd_3.geometry} material={nodes.Hd_3.material} />
      <mesh name="Hd_4" geometry={nodes.Hd_4.geometry} material={nodes.Hd_4.material} />
      <mesh name="mesh_18" geometry={nodes.mesh_18.geometry} material={nodes.mesh_18.material} />
      <mesh name="mesh_18_1" geometry={nodes.mesh_18_1.geometry} material={nodes.mesh_18_1.material} />
      <mesh name="cube_3" geometry={nodes.cube_3.geometry} material={nodes.cube_3.material} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="cube_4" geometry={nodes.cube_4.geometry} material={nodes.cube_4.material} rotation={[-Math.PI, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/models/set1.glb')
